### ISSUE TITLE
Support for ChatGPT Plus

### ISSUE THREAD

**Issue by samwalshnz** [cempehlivan/chatgpt-prompt-chrome-extension#1]
![CleanShot 2023-02-15 at 09 48 21@2x](https://user-images.githubusercontent.com/1085227/218859792-477a3119-7bb1-45fe-91dd-f86870766bc8.png)

I've found your extension really useful. Since upgrading to Plus however, the chrome extension prompt buttons have disappeared; I assume because the CSS selectors for the UI in Plus are different?

**Comment by cempehlivan** [comment]
Hi, I'm glad you like the extension. Unfortunately I can't test it because I don't have a ChatGPT Plus account. If you can send a screenshot of the HTML structure of the middle section from the "Inspect" section of the browser, I can provide an update.

**Comment by cempehlivan** [comment]
Solved with version 0.3.0
